### ISSUE TITLE
Branch name: white background color missing

### ISSUE THREAD

**Issue by nesmyslny** [fisherman/eco#1]
The white background color of the branch name is missing. I'm wondering if it is a bug or just a misconfiguration on my side.

I'm using fish version 2.3.0 and installed eco using fisher.

**Comment by brj** [comment]
I can't repro this and I am also using 2.3.

<img width="563" alt="screen shot 2016-05-29 at 9 21 33 pm 1" src="https://cloud.githubusercontent.com/assets/8317250/15633278/5e2c2c76-25e3-11e6-968a-bd25969db0d6.png">

**Comment by nesmyslny** [comment]
Thank you for the fast reply!

Very strange :( I can't figure out what is wrong.

* I removed all plugins and only installed eco
* I checked it with another terminal, same result
* Cleared my `config.fish`
* Restarted my box :D 

![screenshot_20160529_150118] (https://cloud.githubusercontent.com/assets/4730455/15633516/841614cc-25ae-11e6-95db-ef49389ec013.png)

I'm also confused by the file `fin.fish`. It's not in this repo (fin was the repo that accidentally replaced this one, but I removed all plugins as mentioned before and all files were gone).
Do have an idea how to debug this?

**Comment by nesmyslny** [comment]
Sorry, didn't want to close the issue...

**Comment by nesmyslny** [comment]
Ok, it's only `white` that doesn't work. If I change this line
```fish
set -l branch_color black -b white
```
in `fish_prompt.fish` to
```fish
set -l branch_color black -b fff
```
it shows the white background. But I don't know why :(

**Comment by nesmyslny** [comment]
Setting `TERM=xterm-256color` (instead of `TERM=xterm`) fixed it. I don't know why I was facing this issue now.
Sorry for the inconvenience and thanks again!

**Comment by brj** [comment]
@nesmyslny Ah, that explains it :)
